export {default as Header} from './Header'
export {default as Slider} from './Slider'
export {default as Hero} from './Hero'
export {default as Projects} from './Projects'
export {default as Footer} from './Footer'